language: rust

jobs:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          update: true
          packages:
            - libgtk-3-dev
            - libudev-dev
      env: RELEASE_PKG=borosgui-$TRAVIS_OS_NAME.gz
    - os: macos
      env: RELEASE_PKG=borosgui-$TRAVIS_OS_NAME.zip
    - os: windows
      env: RELEASE_PKG=borosgui-$TRAVIS_OS_NAME.zip

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install p7zip   ; fi

script:
  - cargo build --release
  - ls -lh target/release

before_deploy:
  - if [ "$TRAVIS_OS_NAME" = "osx"   ]; then 7z a -tzip -mx9 $RELEASE_PKG target/release/boros_gui ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then gzip -c -9 target/release/boros_gui > $RELEASE_PKG ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then 7z a -tzip -mx9 $RELEASE_PKG target/release/boros_gui ; fi

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
   secure: WasxmH3+VS7gU3d6HkO+ZyjH9R4plpjH1D36M0wvlHwgFCyXQcRajxVPcOZ75gsC+DZzOzLDAL2BJZoKsTxzuTY8nBKlC/8cxBKAZ0T8ucu/QmYQwhp4lx1gu6rLHOqpxJYeREOT+JyD3j6mulNrX7qS9ayl44qIuWHICRl80JlH1GI3cgEZ0bYYZWtUd7pqWRG73R5rf4Zir1HebK/5ptWB3vIW21JnSkwG1UPif+jVpz9je73X6Xxml//bxyaLFi39AZC/NgOCE8DaFvT/OWRBWoR03vTuvgoMVVrHKQ/7ucPHOwDbvuooYabTKI6SNnFKzjJfg8fiRYMXSahh0nSNcDCXQO4Wusxo63g4DnvP4o9TpJI+n7X/QdxE9CiIScWG67MQKzCnJewSrCPReu1inKL9He/Y/HloSOH5uZQ5qU9SbY48gbYQqOv2ZYzSrbFpn8dL6XemMLIRvd5UzpsEYM0DZp8+amKNXIl5/5x8lLY84wKzlwVZ6kYUxWVkvKW6CnaKE+w+xazQx3d7cjb5O3MLIeCWHkXJuuwEtWtmBqUSIRpcmX9u7p+zNWpgY/W+RTYtXaOTITKGfUjbgkX/AA8mXl/Qnp7TnOotTp379NXsVnTE8bUE0imLxxEwSl+pMQHhIXvYa18OisDPUivQS611NR4Kp8mIvnaJVNw=
  file: $RELEASE_PKG
  skip_cleanup: true
  draft: true
  prelease: false
  name: "Draft to modify"
